### ISSUE TITLE
PFFacebookUtils logInInBackgroundWithReadPermissions block in not executed.

### ISSUE THREAD

**Issue by vickyteke** [ParsePlatform/ParseFacebookUtils-iOS#14]
I upgraded my app to the latest Facebook SDK and Parse SDK and I am using the latest PFFacebookUtils with my Parse iOS SDK. When I use custom login button to invoke PFFacebookUtils logInInBackgroundWithReadPermissions, the block is never called. The only thing that works is when I set 
[PFFacebookUtils facebookLoginManager].loginBehavior = FBSDKLoginBehaviorWeb;

The remaining cases do not work. 
When I use direct Facebook LoginManager to login the user, it works, but it fails every time I use PFFacebookUtils.

All my configuration is correct because it work with FBSDK direct login apis. 

Parse SDK version: Latest 1.9.1
Facebook SDK version: Latest

**Comment by nlutsenko** [comment]
@vickyteke That sounds indeed very strange. Just tested this in our ParseUI repo (it has FB integration setup in a demo project) and it works perfectly.
Can you attach a demo project here, I would gladly dig in deeper...
