### ISSUE TITLE
iOS native ACAccount Support

### ISSUE THREAD

**Issue by codywinton** [ParsePlatform/ParseFacebookUtils-iOS#32]
The Parse Facebook Utils framework used to support using `ACAccount`, but it seems to have been dropped. Please re-add this.

**Comment by nlutsenko** [comment]
Hey @codywinton, actually, this was never a part of Parse Facebook Utils framework, but rather a feature of Facebook SDK itself.
You can specify the behavior that you want when logging in, with something like:
```objc
    [PFFacebookUtils facebookLoginManager].loginBehavior = FBSDKLoginBehaviorSystemAccount;
```
