### ISSUE TITLE
pod have dependancy to   s.dependency 'FBSDKCoreKit', '~> 4.9.0-beta'

### ISSUE THREAD

**Issue by FreudGit** [ParsePlatform/ParseFacebookUtils-iOS#33]
Dependency to "beta", normal?

Is there something new\important in this beta?

Thanks, have a nive week-end

**Comment by nlutsenko** [comment]
Hey @FreudGit, thanks for the question.
Since ParseFacebookUtils needs to support `tvOS` and FB SDK for tvOS is beta only - we do indeed depend on the beta of FBSDK. It's quite stable at this point, so you can safely use it.
