### ISSUE TITLE
20 errors in PFFacebookUtils

### ISSUE THREAD

**Issue by ammarajab** [ParsePlatform/ParseFacebookUtils-iOS#35]
I'm adding facebook login to my xcode parse application. I followed the instructions in the Parse documentation exactly and installed the ParseFacebookUtilsV4 in my project, but when I

import

#import <ParseFacebookUtilsV4/PFFacebookUtils.h>
the PFFacebookUtils.h gives these errors
![screen shot 2015-12-28 at 3 05 20 pm](https://cloud.githubusercontent.com/assets/11994259/12017857/587ef13c-ad75-11e5-8ddc-ecd67071aad3.png)

**Comment by nlutsenko** [comment]
Hey @ammarajab, could you please confirm the version of Xcode you are using? (we support anything from 6.3.2+, but recommended is 7.0+) Also, you might be missing Bolts.framework or Parse.framework in your project - this might produce the similar failures.

Other than that, from the screenshot above - that's all that comes to my mind. If you can post a full error log or a project that has this failure - I might be help you further.

**Comment by henrytkirk** [comment]
It looks like there's an issue with Parse v1.12.0. I had same issue and went back to 1.11.0 and it compiled fine. I updated my pod as so:

pod 'Parse', '~>1.11.0'

**Comment by nlutsenko** [comment]
Latest versions of Parse and ParseFacebookUtils require Xcode 7.0, it's a good call to use the old version which is stable and works good if you can't update to Xcode 7 just yet, otherwise I recommend updating.

**Comment by henrytkirk** [comment]
I am on Xcode 7.2. There's definitely something funky going on with Parse 1.12.0. That's the only pod that had changed since my last build that worked.

**Comment by nlutsenko** [comment]
@henrytkirk - is it the same issue? Can you add post more details? Will definitely help you, just trying to get more info first.

**Comment by henrytkirk** [comment]
It was - for me, the combo of Parse 1.12.0, ParseFacebookUtilsV4 1.9.1, and ParseTwitterUtils 1.10.0 is where it would generate those same build errors (even after cleaning, and deleting derived data). I fixed it by rolling back to Parse 1.11.0. I didn't dig too deep into what could have been the issue.

**Comment by nlutsenko** [comment]
Interesting thing here - if you update all of them to the latest, it should work flawlessly.

**Comment by henrytkirk** [comment]
Here's output from when I updated pods earlier:
...
Using Bolts (1.5.1)
Using FBSDKCoreKit (4.8.0)
Using FBSDKLoginKit (4.8.0)
Installing Parse 1.12.0 (was 1.11.0)
Using ParseFacebookUtilsV4 (1.9.1)
Installing ParseTwitterUtils 1.10.0 (was 1.9.1)
Using ParseUI (1.1.7)
...

**Comment by nlutsenko** [comment]
Latest version of ParseFacebookUtilsV4 is 1.11.0, maybe that's the problem.

**Comment by henrytkirk** [comment]
With that combo - it won't update. Maybe a dependency is preventing it from updating?

**Comment by nlutsenko** [comment]
That might be it. Can you post your Podfile here?

**Comment by henrytkirk** [comment]
That was pretty much it - the rest are some private internal pods (that don't depend on bolts or anything) and AFNetworking.

**Comment by henrytkirk** [comment]
Looks like i'm not the only one with the issue:
http://stackoverflow.com/questions/34695199/cant-using-parse-facebook-authentification/34700096#34700096

**Comment by nlutsenko** [comment]
Will look deeper into it and try to reproduce the issue.

**Comment by ammarajab** [comment]
For me I solved the problem.
It turns out I was using an old version of parse and bolts 
once I updated them to the latest version it worked fine

**Comment by ammarajab** [comment]
P.S. I'm using the latest everything now xcode, parse, bolts, FacebookSDK.

**Comment by hutchy** [comment]
I've just ran into the same issue, I ran pod update and then hit the errors as detailed as above.

Revlevant pods detailed below:

Installing Bolts 1.5.1 (was 1.3.0)
Installing FBSDKCoreKit 4.8.0 (was 4.6.0)
Installing FBSDKLoginKit 4.8.0 (was 4.6.0)
Installing Parse 1.12.0 (was 1.8.5)
Installing ParseFacebookUtilsV4 1.9.1 (was 1.8.5)
Installing ParseTwitterUtils 1.10.0 (was 1.8.5)

**Comment by abingeorgev** [comment]
Using Bolts (1.5.1)
Using FBSDKCoreKit (4.8.0)
Using FBSDKLoginKit (4.8.0)
Using Mixpanel (2.9.1)
Using Parse (1.12.0)
Using ParseFacebookUtilsV4 (1.9.1).

I am having the same issue here. I had sent you my project @nlutsenko, at your mail. Please check.

**Comment by abingeorgev** [comment]
Hi, @nlutsenko, as you said the latest version of Parsefacebbokutilsv4 is 1.11, I just updated my pods to,
pod 'ParseFacebookUtilsV4','~>1.11.0'. And guess what, it worked. Sadly am getting beta versions of FBSDKs. Glad it worked. 

Using Bolts (1.5.1)
Installing FBSDKCoreKit 4.9.0-beta2 (was 4.8.0)
Installing FBSDKLoginKit 4.9.0-beta2 (was 4.8.0)
Using Mixpanel (2.9.1)
Using Parse (1.12.0)
Installing ParseFacebookUtilsV4 1.11.0 (was 1.9.1).

**Comment by henrytkirk** [comment]
In my case it was not out-updating to 1.11.0 for ParseFacebookUtilsV4. I will try forcing it and see if that helps.

**Comment by nlutsenko** [comment]
Quick update here:
- Usage of beta FBSDK is intentional, as only the beta version has `tvOS` support.
- Retested the entire thing from scratch multiple times, and the entire project compiles for me without a glitch or anything.
- Used `Podfile`:
```
use_frameworks!

pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'ParseUI'
```
- My `Podfile.lock`:
```
PODS:
  - Bolts (1.5.1):
    - Bolts/AppLinks (= 1.5.1)
    - Bolts/Tasks (= 1.5.1)
  - Bolts/AppLinks (1.5.1):
    - Bolts/Tasks
  - Bolts/Tasks (1.5.1)
  - FBSDKCoreKit (4.9.0-beta2):
    - Bolts (~> 1.5)
  - FBSDKLoginKit (4.9.0-beta2):
    - FBSDKCoreKit (~> 4.9.0-beta)
  - Parse (1.12.0):
    - Bolts/Tasks (~> 1.5)
  - ParseFacebookUtilsV4 (1.11.0):
    - Bolts/Tasks (>= 1.5)
    - FBSDKCoreKit (~> 4.9.0-beta)
    - FBSDKLoginKit (~> 4.9.0-beta)
    - FBSDKTVOSKit (~> 4.9.0-beta)
    - Parse (~> 1.11)
  - ParseUI (1.1.7):
    - Bolts/Tasks (~> 1.3)
    - Parse (~> 1.9)

DEPENDENCIES:
  - Parse
  - ParseFacebookUtilsV4
  - ParseUI

SPEC CHECKSUMS:
  Bolts: a12663244b1d3351c738882e71902fc74db54f64
  FBSDKCoreKit: d49cbf69741e3c5732166ec9ff4cbd9b288dd53e
  FBSDKLoginKit: d32e83c0d2d39ef74a942543cacae2dc4de7d088
  Parse: de2c52a9a1421b91ae7594ab8ce191afd184f19b
  ParseFacebookUtilsV4: 216e03bd560404eed09a4875c75f0c1cdf758070
  ParseUI: c2bcdfbb00330e464b5b773266ae221697a3bb7b

COCOAPODS: 0.39.0
```

Few things that I recommend at all times when it comes to CocoaPods and Xcode:
- Update the local checkout of CocoaPods repo: `pod repo update`
- Remove Xcode DerivedData complete (usually in `~/Library/Developer/Xcode/DerivedData`)
- Remove `Pods` subfolder in your project
- Run `pod update`

**Comment by makthrow** [comment]
I think the issue, as confirmed by previous posters, is cocoapods installing v.1.9.1 of ParseFacebookUtilsV4   when it should install 1.11.0

in my case, doing pod repo update and all the other recommendations still didn't get cocoapods to install the correct ParseFacebookUtilsV4

any other suggestions?

**Comment by nlutsenko** [comment]
Post your `Podfile` here? Maybe there is a weird dependency problem?

**Comment by makthrow** [comment]
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

xcodeproj 'grocerydate'

target 'grocerydate' do
    pod 'Parse'
    pod 'ParseUI'
    pod 'Bolts'
    pod 'ParseFacebookUtilsV4'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'

end



by changing to     pod 'ParseFacebookUtilsV4','~>1.11.0' 
it starts working

**Comment by abingeorgev** [comment]
Yea, thats what worked for me. pod 'ParseFacebookUtilsV4','~>1.11.0'

**Comment by henrytkirk** [comment]
so why is it not updating w/o forcing it? is this a cocoa pod bug we need to file?

**Comment by livingstonef** [comment]
Can I just ask what version of Cacoapods everyone is using? Just updated to cocoapods-1.0.0.beta.2 and it seems it has made redundant quite a lot of podspecs, and the only work around will be to wait for these to be updated.

**Comment by digicub** [comment]
Had the same problem. Updating ParseFacebookUtilsV4 worked for me too. Must be a config bug?

**Comment by wbroek** [comment]
Had the same problem but solved it to update the Facebook SDK (FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit) first to 4.9.0 and then Parse and ParseFacebookUtilsV4.
Looks like latest ParseFacebookUtilsV4 needs 4.9.0 but cocoa pods does not update them automatically

**Comment by nlutsenko** [comment]
Official FBSDK 4.9.0 is out since last week, I suggest everyone on this thread trying to update/install pods once again. Please comment here if you still run into any issues.

**Comment by gilthonweapps** [comment]
Hi,

When updating ParseFacebookUtilsV4 to 1.11.0 with cocoapods, it won't use the latest version of FBSDKCoreKit which is 4.10.0.
I think the podspec of ParseFacebookUtilsV4 needs to be updated.

My Podfile:

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Parse'
pod 'ParseFacebookUtilsV4', '~> 1.11.0'
pod 'ParseTwitterUtils'
pod 'ParseUI'

ParseFacebookUtilsV4 doesn't allow me to use version 4.10.0 of FBSDKCoreKit and FBSDKLoginKit.

**Comment by jefflai** [comment]
I'm getting the same issue where I'm not able to use ParseFacebookUtilsV4 version 1.11.0 with FBSDKCoreKit and FBSDKLoginKit version 4.10.0 @nlutsenko @gilthonweapps

**Comment by nlutsenko** [comment]
Hey everyone, I am working on updating the entire thing, should be avaialble shortly.

**Comment by jefflai** [comment]
awesome thanks! @nlutsenko

**Comment by mitchellporter** [comment]
Thanks @nlutsenko :)

**Comment by deada92** [comment]
I just run into the same error with this podfile:

file:
xcodeproj 'PrayForTheWorld.xcodeproj'

use_frameworks!

pod 'MMPopupView'
pod 'EMCCountryPickerController', '~> 1.0'
pod 'KVNProgress'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'BButton'
pod 'UALogger', '~> 0.3'
pod 'Parse'
pod 'Bolts'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils'
pod 'FBSDKShareKit'
pod 'pop', '~> 1.0'
pod 'PermissionScope'

Output:
Downloading dependencies
Using BButton (4.0.2)
Using Bolts (1.6.0)
Using EMCCountryPickerController (1.3.3)
Installing FBSDKCoreKit 4.10.0 (was 4.9.1)
Installing FBSDKLoginKit 4.10.0 (was 4.9.1)
Installing FBSDKShareKit 4.10.0 (was 4.9.1)
Using Fabric (1.6.5)
Using KVNProgress (2.2.2)
Using MMPopupView (1.6)
Using Masonry (0.6.4)
Using Parse (1.12.0)
Installing ParseFacebookUtilsV4 1.9.1 (was 1.11.0)
Using ParseTwitterUtils (1.10.0)
Using PermissionScope (1.0.2)
Using TwitterCore (1.15.1)
Using TwitterKit (1.15.1)
Using UALogger (0.3)
Installing pop 1.0.9 (was 1.0.8)
Generating Pods project

**Comment by nlutsenko** [comment]
Update is pending to be released next week with the updated dependencies on FBSDK.
If anyone wants to use it right now - you can specify the master branch for updating ParseFacebookUtilsV4 podspec - it will pickup the new podspec that was already updated.

**Comment by Perjan** [comment]
Hey guys this is what worked for me:

1. pod repo update
2. pod update

Have fun!

**Comment by jgalperin** [comment]
In my case I was using carthage through ParseKit, and banging my head against the wall. 

Anyone in need of an urgent fix, I recommend grabbing the **ParseFacebookUtilsV4** framework from the [SDK](https://parse.com/apps/quickstart#parse_data/mobile/ios/swift/existing) and adding it to xCode manually.

**Comment by ryderjack** [comment]
Hey guys, same issue using ParseFacebookUtilsV4 1.11.0 with the latest FBSDKs.

When's ParseFacebookUtilsV4 1.11.1 out?

Cheers
