### ISSUE TITLE
Login Button is not showing up

### ISSUE THREAD

**Issue by makthrow** [ParsePlatform/ParseFacebookUtils-iOS#42]
I don't know if it's something I'm doing, but once I updated to the latest parsebookutils,

my old facebook login button is not showing up. All I see is the parse signup fields.

here are my code:

Viewcontroller:
https://gist.github.com/makthrow/ee54d3d036dc141037e4

LoginViewController:
https://gist.github.com/makthrow/cb57eb7d45ab5a8d8915

**Comment by makthrow** [comment]
putting 
fields [PFLoginFields.Facebook] 

in my LoginViewController, makes the button show up again

**Comment by nlutsenko** [comment]
Found the bug, indeed it's valid. 
Nice catch, and thanks for reporting this as well as including the code snippet!

Workaround: 
Move setter for fields all the way above just after the construction of `LogInViewController` aka
```swift
let loginViewController = LoginViewController()
loginViewController.fields = [PFLogInFields.Facebook, PFLogInFields.Default]
loginViewController.delegate = self
loginViewController.facebookPermissions = ["public_profile", "email", "user_friends", "user_education_history", "user_birthday"]
loginViewController.signUpController?.delegate = self
```

It happens because we only setup handlers for all the buttons once (on `viewDidLoad`), which is no longer valid, as we allow changing the fields at any time. Sending a PR with a fix in a second.

**Comment by makthrow** [comment]
Hey nlutsenko, thank you for the reply.

I tried your code and it still didn't work.

**Comment by nlutsenko** [comment]
Are you using the latest ParseUI? (1.2.0)

**Comment by makthrow** [comment]
How do I check what versions of pods I am using?

**Comment by makthrow** [comment]
pot outdated

tells me everything is fine

**Comment by nlutsenko** [comment]
Can you paste your `Podfile.lock` or a portion of it here?
I clearly reproduced the issue you've seen and the workaround suggested above worked great for me.

**Comment by makthrow** [comment]
PODS:
  - Bolts (1.6.0):
    - Bolts/AppLinks (= 1.6.0)
    - Bolts/Tasks (= 1.6.0)
  - Bolts/AppLinks (1.6.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.6.0)
  - FBSDKCoreKit (4.9.0-beta2):
    - Bolts (~> 1.5)
  - FBSDKLoginKit (4.9.0-beta2):
    - FBSDKCoreKit (~> 4.9.0-beta)
  - Firebase (2.5.0)
  - JSQMessagesViewController (7.2.0):
    - JSQSystemSoundPlayer (~> 2.0.1)
  - JSQSystemSoundPlayer (2.0.1)
  - Parse (1.12.0):
    - Bolts/Tasks (~> 1.5)
  - ParseFacebookUtilsV4 (1.11.0):
    - Bolts/Tasks (>= 1.5)
    - FBSDKCoreKit (~> 4.9.0-beta)
    - FBSDKLoginKit (~> 4.9.0-beta)
    - FBSDKTVOSKit (~> 4.9.0-beta)
    - Parse (~> 1.11)
  - ParseTwitterUtils (1.10.0):
    - Bolts/Tasks (~> 1.5)
    - Parse (~> 1.9)
  - ParseUI (1.1.7):
    - Bolts/Tasks (~> 1.3)
    - Parse (~> 1.9)
  - SwiftyJSON (2.3.2)

DEPENDENCIES:
  - Bolts
  - FBSDKCoreKit
  - FBSDKLoginKit
  - Firebase (>= 2.5.0)
  - JSQMessagesViewController (~> 7.2)
  - Parse
  - ParseFacebookUtilsV4 (~> 1.11.0)
  - ParseTwitterUtils
  - ParseUI
  - SwiftyJSON (from `https://github.com/SwiftyJSON/SwiftyJSON.git`)

EXTERNAL SOURCES:
  SwiftyJSON:
    :git: https://github.com/SwiftyJSON/SwiftyJSON.git

CHECKOUT OPTIONS:
  SwiftyJSON:
    :commit: 929539eb6a3304eaa9153ca44041a78b85bf2ee5
    :git: https://github.com/SwiftyJSON/SwiftyJSON.git

SPEC CHECKSUMS:
  Bolts: f52a250053bb517ca874523c3913776359ab3def
  FBSDKCoreKit: d49cbf69741e3c5732166ec9ff4cbd9b288dd53e
  FBSDKLoginKit: d32e83c0d2d39ef74a942543cacae2dc4de7d088
  Firebase: 744617c0733b45198f9486ebd5cac64ec2d10d79
  JSQMessagesViewController: 73cab48aa92fc2d512f3b6724f3425cc47a19eb5
  JSQSystemSoundPlayer: c5850e77a4363ffd374cd851154b9af93264ed8d
  Parse: de2c52a9a1421b91ae7594ab8ce191afd184f19b
  ParseFacebookUtilsV4: 216e03bd560404eed09a4875c75f0c1cdf758070
  ParseTwitterUtils: 8856ac80da50bbb0f0bcf251def20b62e1ae6bc4
  ParseUI: c2bcdfbb00330e464b5b773266ae221697a3bb7b
  SwiftyJSON: 04ccea08915aa0109039157c7974cf0298da292a

COCOAPODS: 0.39.0

**Comment by nlutsenko** [comment]
I suggest you try updating once again together with `pod repo update` first.
Let me know if it works (if it gets updated to `1.2.0`) as well as whether the workaround specified above works.

**Comment by makthrow** [comment]
Alans-MacBook-Pro:butterfly airjaw$ pod repo update
Updating spec repo `master`
Already up-to-date.

CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Alans-MacBook-Pro:butterfly airjaw$ pod repo update
Updating spec repo `master`
Updating 4219dd9..c722ae7
Fast-forward
 Specs/ParseUI/1.2.0/ParseUI.podspec.json | 49 ++++++++++++++++++++++++++++++++
 1 file changed, 49 insertions(+)
 create mode 100644 Specs/ParseUI/1.2.0/ParseUI.podspec.json
From https://github.com/CocoaPods/Specs
   4219dd9..c722ae7  master     -> origin/master

CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.



What the heck, cocoapods... These were typed minutes apart

**Comment by makthrow** [comment]
So yea, there's a bug with cocoapods. 
i just tried with another podfile.

you have to run 
pod repo update
twice. and it'll update ParseUI to 1.2 on the second try

**Comment by nlutsenko** [comment]
Maybe caching issues? You might try killing your local cache from `~/.cocoapods`.

**Comment by makthrow** [comment]
Still not working for me.

I have one project, where i create a 
PFLoginViewController

and another where I override it so I can customize it with a special background.

The overridden one doesn't show the custom button.

when i add 
fields=[PFLoginFields.Facebook] 
 to the overridden PFLoginViewController file, it shows the button (but the button is unclickable)

**Comment by nlutsenko** [comment]
Definitely sounds weird, as I've tested this with one of our demo projects on [ParseUI](https://github.com/ParsePlatform/ParseUI-iOS) and the code above.
Any chance you can try to get to the source of truth by using breakpoints and inspecting view layout (the latter would help tremendously).

**Comment by makthrow** [comment]
Do you mind posting a gist of your view controller and login viewcontroller

here are mine

https://gist.github.com/makthrow/b647b4c367e111a76f8c

https://gist.github.com/makthrow/1930998a4a520aec893f

**Comment by nlutsenko** [comment]
Sure, here is the gist: https://gist.github.com/nlutsenko/8b381a64e47726bf9dc1
Result on screen: 
![simulator screen shot jan 12 2016 7 46 25 pm](https://cloud.githubusercontent.com/assets/606991/12284546/32606b2e-b965-11e5-8791-345c7b616909.png)
Also, the Facebook button is tappable, according to this screenshot (it actually opens the Safari piece if I release the touch):
![simulator screen shot jan 12 2016 7 46 28 pm](https://cloud.githubusercontent.com/assets/606991/12284552/47dab842-b965-11e5-83d7-af89e2c263cb.png)

**Comment by makthrow** [comment]
OK I figured out what happened.

in my appdelegate, if the user is not signed in,

i am sending them to my custom loginViewController.

that's why if I add
fields = [.Facebook]  there, the button shows but doesn't do anything because I didn't set any delegates for it


I'm not sure why this code actually worked before the update to latest pods

thank you for your help, guess this isn't a bug

**Comment by nlutsenko** [comment]
Glad you worked it out!
There is still a small issue here, that we caught with your help!
Let me know if there is anything else...
