### ISSUE TITLE
Could not build Objective-C module ParseFacebookUtilsV4

### ISSUE THREAD

**Issue by AndrewSB** [ParsePlatform/ParseFacebookUtils-iOS#43]
Hey!

Trying to get ParseFacebookUtilsV4 to work with a vanilla Swift 2, Xcode 7 project.

I'm using https://github.com/flovilmart/ParseKit to pull in ParseFacebookUtils-iOS, when I try to build (after importing ParseFacebookUtilsV4 into my AppDelegate) I get this output: 
![screen shot 2016-01-12 at 5 59 24 pm](https://cloud.githubusercontent.com/assets/3814772/12282833/41974158-b956-11e5-9a2c-a44dbd345b6e.png)

Any ideas on how to resolve?

**Comment by nlutsenko** [comment]
Any chance you are using old version of Bolts? (recommended is 1.6.0)

**Comment by AndrewSB** [comment]
using `github "BoltsFramework/Bolts-iOS" "1.6.0"`, thanks for the quick response!
Any other ideas?

**Comment by nlutsenko** [comment]
Hmmm... There might be an issue when using an old `ParseFacebookUtilsV4` and new `Parse`.
@flovilmart any chance you can update the submodule reference to the latest, since `ParseKit` is your repo?

**Comment by AndrewSB** [comment]
@nlutsenko I've already created a PR (https://github.com/flovilmart/ParseKit/pull/1) and I'm actually using my branch through Carthage for this project, versions are 

"ParsePlatform/Parse-SDK-iOS-OSX" "9eeea3f24acb6f676ee498763feff44cd1074bf4"
ParsePlatform/ParseFacebookUtils-iOS" "ebb4b4923e54d5e5303db88f632d06cdd388530c"

**Comment by nlutsenko** [comment]
And with those - it still doesn't work? :(
Is there a chance you can paste a log for at least some of the errors in `PFFacebookUtils.h` in that case?

**Comment by AndrewSB** [comment]
Wait, just realized that I may not have completely understood how ParseKit works. I might have needed to build the frameworks using something in the `scripts/` directory.
So I may be using a much older version of the libraries.

Let's wait for @flovimart to chime in

**Comment by flovilmart** [comment]
@AndrewSB in order to build all the frameworks you have to use the scripts provided. We (I) should put Parse as a Carthage dependency now instead of the manual build. What do you think?

**Comment by nlutsenko** [comment]
Parse and Bolts as dependency in your repo sounds like a great idea!
Let me know if you need any help...

**Comment by AndrewSB** [comment]
@flovilmart I totally agree, just made a PR to do that. Let me check to see if running those scripts fixed the issues I was having with the PFFacebookUtilsV4 framework

**Comment by flovilmart** [comment]
@nlutsenko I have problems building parse on my machine through Carthage. 
@andrewsb thanks for the PR :)

**Comment by AndrewSB** [comment]
Hmmm, I'm still having a bunch of errors come up. Let me try after deleting `Carthage/` and updating again

**Comment by nlutsenko** [comment]
@flovilmart, it clearly passes for me on the latest release tag as well as on master.
Any chance you can point to more things?

**Comment by flovilmart** [comment]
@nlutsenko, we are currently in a release rush. I'll try to have a better look before e.o.w.

**Comment by AndrewSB** [comment]
F.Y.I., realized this is a dupe of https://github.com/ParsePlatform/ParseFacebookUtils-iOS/issues/35, just through https://github.com/flovilmart/ParseKit

**Comment by nlutsenko** [comment]
Yup, you are right... Closing this one out, since it's clearly a duplicate.
