### ISSUE TITLE
'UIKit/UIKit.h' not found

### ISSUE THREAD

**Issue by AndrewSB** [ParsePlatform/ParseFacebookUtils-iOS#45]
Trying to build the project locally, I've downloaded a zip of the latest release (https://github.com/ParsePlatform/ParseFacebookUtils-iOS/releases/tag/v4-1.11.0) and done a `bundle install` and `pod update`.

I'm being given a bunch of errors saying `'UIKit/UIKit.h' not found` is not found in a bunch of files:
<img width="1280" alt="screen shot 2016-01-18 at 6 53 21 pm" src="https://cloud.githubusercontent.com/assets/3814772/12408403/f05399fe-be14-11e5-8898-a86900d6183d.png">

Would love some advice on how to fix this build issue

**Comment by nlutsenko** [comment]
Few things here:
- Run `git submodule update --init --recursive` to pull in all dependencies
- It will force `My Mac` as unavailable destination (we are using shared configs from a submodule across all repos)
- Close Xcode, open Xcode - try again.

Let me know if this helps.

**Comment by AndrewSB** [comment]
Updating submodules worked, proposed https://github.com/ParsePlatform/ParseFacebookUtils-iOS/pull/46

**Comment by nlutsenko** [comment]
Perfect! Reviewing now.
