### ISSUE TITLE
Dependencies Are Out of Date

### ISSUE THREAD

**Issue by mrchristopher124** [ParsePlatform/ParseFacebookUtils-iOS#52]
Trying to use the latest facebook iOS SDK reverts back to some older version of ParseFacebookUtilsV4. 

Depends on:	
Bolts/Tasks	>= 1.5
Parse	~> 1.11
FBSDKCoreKit	~> 4.9.0-beta
FBSDKLoginKit	~> 4.9.0-beta
FBSDKTVOSKit	~> 4.9.0-beta
 	
-----

Installing FBSDKCoreKit 4.10.0 (was 4.9.1)
Installing FBSDKLoginKit 4.10.0 (was 4.9.1)
Installing FBSDKShareKit 4.10.0 (was 4.9.1)
Installing ParseFacebookUtilsV4 1.9.1 (was 1.11.0)

**Comment by deada92** [comment]
push! It gives me xxxxx errors ...

**Comment by ghugues** [comment]
I see that you have fixed the podspec, but could you also push a fix to the current podfile that sets the dependency for Facebook SDKs to something like "~> 4.9" instead of "~> 4.9.0-beta" ?
Thanks

**Comment by codywinton** [comment]
Please update this

**Comment by nlutsenko** [comment]
New version is out, should be all good now.
