### ISSUE TITLE
Framework not building on xCode 7.3 (Not Using CocoaPods)

### ISSUE THREAD

**Issue by raffi23** [ParsePlatform/ParseFacebookUtils-iOS#56]
![screen shot 2016-04-04 at 12 27 32 pm](https://cloud.githubusercontent.com/assets/6380048/14243952/2585cbdc-fa61-11e5-98f4-d819c4d8cd19.png)

is there any workaround for this issue?

**Comment by nlutsenko** [comment]
This looks like a very old version of ParseFacebookUtilsV4 and newest version of Parse framework, that's why the errors appear, since there is no more `PF_GENERIC` 
Can you make sure you are using the latest version available?

**Comment by raffi23** [comment]
I am really sorry for the confusion, I just realized that I was using an old version.
Thanks for the help.
