### ISSUE TITLE
Which Facebook SKD's framework include

### ISSUE THREAD

**Issue by iStopped** [ParsePlatform/ParseFacebookUtils-iOS#73]
I have builded the ParseFacebookUtils.framework from source, but I'm wondering which Facebook SDK's file I've to include in my project. I guess only FBSDKCoreKit.framework?

**Comment by AmbroiseCollon** [comment]
You need FBSDKLoginKit too. But if you use pods, they are installed with ParseFacebookUtils so you shouldn't care.
