### ISSUE TITLE
logInInBackground creating empty record for user

### ISSUE THREAD

**Issue by paiv** [ParsePlatform/ParseFacebookUtils-iOS#81]
I'm in process of developing an app, and have this line for login:

    PFFacebookUtils.logInInBackground(withReadPermissions: ["public_profile", "email"]) { ...

At some point in the past, like three months ago, this was returning PFUser with `firstName`, `lastName`, `email` fields, and a new record appearing on backend (back4app) with these fields filled.

A couple of weeks ago client reported that user has empty fields.

So I cleaned up my user, and logged it again. While login steps appeared the same, user now had empty fields returned in callback, as well as on backend.

Now my question is, should I start making Facebook Graph queries myself to fill user fields, or they should be filled automatically when user signups with Facebook account, but I'm missing something?

**Comment by jesuslg123** [comment]
We are facing the same issue, any idea what is going on?

**Comment by paiv** [comment]
This is my first app with Parse, so I'm not aware how it was intended. It might be a change on Facebook side.

For now, I added a query for these fields after user signups. This might be an extra API call, but it's acceptable workaround.

**Comment by Beninho85** [comment]
It has always been like that. When you create it for the first time, it's create an empty user with only authData filled, you have to get facebooked id and make the call

**Comment by paiv** [comment]
OK, thank you
